spring.application.name=Careplan
spring.datasource.url=jdbc:mysql://localhost:3306/careplan
spring.datasource.username=root
spring.datasource.password=1234
# Automatically creates/updates your MySQL tables based on your Java models
spring.jpa.hibernate.ddl-auto=update